apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-nats-subscriber-chart.fullname" . }}
  labels:
  {{- include "finops-nats-subscriber-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-nats-subscriber-chart.fullname" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "finops-nats-subscriber-chart.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
